name: Trigger Netlify Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger netlify build hook
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"trigger_branch":"main","env":{"REBUILD_SPEC":"true"}}' \
            https://api.netlify.com/build_hooks/686f025c6cf5570547a62f91
